apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-scheduler
  namespace: kube-system
  labels:
    app: my-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-scheduler
  template:
    metadata:
      labels:
        app: my-scheduler
    spec:
      serviceAccountName: extender
      nodeSelector:
        kubernetes.io/hostname: cn-shanghai.192.168.1.211 
      volumes:
      - name: my-scheduler-config
        hostPath:
          path: /root/qpli/extender/k8s-scheduler-extender-example/extender/scheduler-config.json
          type: FileOrCreate
      containers:
      - name: my-scheduler-ctr
        image: registry-vpc.cn-shanghai.aliyuncs.com/acs/kube-scheduler:v1.12.6-aliyun.1
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --address=127.0.0.1
        - --policy-config-file=/my-scheduler/scheduler-config.json
        - --leader-elect=true
        volumeMounts:
        - name: my-scheduler-config
          mountPath: /my-scheduler/scheduler-config.json
